title: Simple Page
preset: page

icon: 📝

status:
  draft: true
  unlisted:
    label: Hidden Page
    text: The page is not listed in the main menu
  listed:
    label: Menu Page
    text: The page is listed in the main menu

options:
  changeTemplate: 
    admin: true
    editor: false
  changeTitle: 
    admin: true
    editor: false
  delete: 
    admin: true
    editor: false
  update: 
    admin: true
    editor: false
  status: 
    admin: true
    editor: false

pages:
  template: default

fields:

  panorama:
    type: files
    multiple: false
    translate: false 
    query: page.images
    width: 1/2
            
  thumbnail:
    type: files
    multiple: false
    translate: false 
    query: page.images
    width: 1/2

  mapToggle:
    label: Show global map
    type: toggle
    width: 1/3

  columnToggle:
    label: Use columns for the text
    type: toggle
    width: 1/3

  whiteToggle:
    label: White Background
    type: toggle
    width: 1/3

    
  text:
    type: textarea
    size: huge
