title: Simple Page
preset: page

icon: 📝

status:
  draft: true
  unlisted:
    label: Hidden Page
    text: The page is not listed in the main menu
  listed:
    label: Menu Page
    text: The page is listed in the main menu

pages:
  template: default

fields:

  panorama:
    type: files
    multiple: false
    translate: false 
    query: page.images

  mapToggle:
    label: Show global map
    type: toggle

  columnToggle:
    label: Use columns for the text
    type: toggle
    
  text:
    type: textarea
    size: huge
