title: Product
fields:
  description:
    label: Description
    type: text
  price:
    label: Price
    type: number
    required: true
    min: 100
    step: .01
    width: 1/2
  tax:
    label: Tax
    type: number
    required: true
    step: 1
    min: 0
    max: 100
    after: %
    width: 1/2