title: Site


tabs:
  content:
    label: Content
    icon: text
    columns:
      - width: 1/2
        sections:
          cases: sections/cases
          # practices: sections/practices
      - width: 1/2
        sections:
          notes: sections/notes
          pages:
            type: pages
            create: default
            template:
              - about
              - home
              - default
              - map
      - width: 1
        fields:
          practice-head:
            type: headline
            label: Practice
            numbered: false
      - width: 1
        sections:
          drafts:
            extends: sections/practices
            headline: Drafts
            status: draft

      - width: 1/4
        sections:
          bigpictures:
            extends: sections/bigpictures
            status: listed
      - width: 1/4
        sections:
          peoples:
            extends: sections/peoples
            status: listed

      - width: 1/4
        sections:
          scenarios:
            extends: sections/scenarios
            status: listed

      - width: 1/4
        sections:
          forms:
            extends: sections/forms
            status: listed
  settings:
    label: Settings
    icon: text
    columns:
      - width: 1/2
        fields:
          maintenance:
            label: Maintenance
            type: toggle
            text: Enable Maintenance
            translate: false
          share:
            label: Share on
            type: checkboxes
            options:
              facebook: Facebook
              twitter: Twitter
              pinterest: Pinterest
            help:  Enable the icons to share content on social network.
          facebook-id:
            label: Facebook page title
            type: text
          twitter-id:
            label: Twitter
            type: text
            placeholder: @twitter-account

      - width: 1/2
        fields:
          projectbgcolor:
            type: color
            editableAlpha: false
            default: "#000000"
            presets:
              - "#000000"
              - "#FFFFFF"
              - "#F2E0CD"
          projecttxtcolor:
            type: color
            editableAlpha: false
            default: "#FFFFFF"
            presets:
              - "#000000"
              - "#FFFFFF"
              - "#F2E0CD"
          description:
            label: Description
            type:  textarea
          keywords:
            label: Keywords
            type:  tags
          ogimage:
            label: Site Thumbnail
            type:  url
            help:  URL of the thumbnail that will represent your website on the social networks.
            translate: false
