title: Site


tabs:
  content:
    label: Content
    icon: text
    columns:
      - width: 1/2
        sections:
          cases: sections/cases
          # practices: sections/practices
      - width: 1/2
        sections:
          notes: sections/notes
          pages:
            type: pages
            create: default
            template:
              - about
              - home
              - default
              - map
      - width: 1
        fields:
          practice-head:
            type: headline
            label: Practice
            numbered: false
      - width: 1
        sections:
          drafts:
            extends: sections/practices
            headline: Drafts
            status: draft

      - width: 1/4
        sections:
          bigpictures:
            extends: sections/bigpictures
            status: listed
      - width: 1/4
        sections:
          peoples:
            extends: sections/peoples
            status: listed

      - width: 1/4
        sections:
          scenarios:
            extends: sections/scenarios
            status: listed

      - width: 1/4
        sections:
          forms:
            extends: sections/forms
            status: listed
  settings:
    label: Settings
    icon: text
    columns:
      - width: 1/2
        sections:
          param1:
            type: fields 
            fields:
              practicetxt:
                label: Practice label
                type: text
                default: Practice
                width: 1/2
              casestxt:
                label: Cases label
                type: text
                default: Cases
                width: 1/2
              studiotxt:
                label: Studio label
                type: text
                default: Studio
                width: 1/2
              line:
                type: line
              bigpicturetxt:
                label: Big picture label
                type: text
                default: Big picture
                width: 1/2
              peopletxt:
                label: People label
                type: text
                default: People
                width: 1/2
              scenariotxt:
                label: Scenario label
                type: text
                default: Scenario
                width: 1/2
              formtxt:
                label: Form label
                type: text
                default: Form
                width: 1/2

      - width: 1/2
        sections:
          param2:
            type: fields 
            fields:
              maintenance:
                label: Maintenance
                type: toggle
                text: Enable Maintenance
                translate: false
                width: 1/2
              newsletterform:
                label: Newsletter form
                type: toggle
                text: Enable Newsletter form
                translate: false
                width: 1/2
              projectbgcolor:
                type: color
                editableAlpha: false
                default: "#000000"
                presets:
                  - "#000000"
                  - "#FFFFFF"
                  - "#F2E0CD"
                width: 1/2
              projecttxtcolor:
                type: color
                editableAlpha: false
                default: "#FFFFFF"
                presets:
                  - "#000000"
                  - "#FFFFFF"
                  - "#F2E0CD"
                width: 1/2
              description:
                label: Description
                type:  textarea
              keywords:
                label: Keywords
                type:  tags
              # ogimage:
              #   label: Site Thumbnail
              #   type:  url
              #   help:  URL of the thumbnail that will represent your website on the social networks.
              #   translate: false
              logo:
                label: Logo
                type: files
                query: site.images
                multiple: false
                translate: false
                layout: cards
                size: small
                help: if none, default RalstonBau logo
          logos:
            type: files
            headline: Fichiers SVG
            layout: list
            template: logo
            info: "{{ file.dimensions }}"
            image:
              # ratio: 5/4
              back: white
              # cover: true
            # min: 1
            size: medium
  analytics:
    label: Analytics
    icon: refresh
    columns:
      - width: 3/4
        sections:
          main:
            type: matomo-main
      - width: 1/4
        sections:
          sidebar:
            type: matomo-sidebar
