title: Site


tabs:
  content:
    label: Content
    icon: text
    columns:
      - width: 1/2
        sections:
          cases: sections/cases
          # practices: sections/practices
      - width: 1/2
        sections:
          notes: sections/notes
          pages:
            type: pages
            create: default
            template:
              - about
              - home
              - default
              - map
      - width: 1
        fields:
          practice-head:
            type: headline
            label: Practice
            numbered: false
      - width: 1
        sections:
          drafts:
            extends: sections/practices
            headline: Drafts
            status: draft

      - width: 1/4
        sections:
          bigpictures:
            extends: sections/bigpictures
            status: listed
      - width: 1/4
        sections:
          peoples:
            extends: sections/peoples
            status: listed

      - width: 1/4
        sections:
          scenarios:
            extends: sections/scenarios
            status: listed

      - width: 1/4
        sections:
          forms:
            extends: sections/forms
            status: listed
  settings:
    label: Settings
    icon: text
    columns:
      - width: 1/2
        sections:
          param1:
            type: fields 
            fields:
              maintenance:
                label: Maintenance
                type: toggle
                text: Enable Maintenance
                translate: false
              practicetxt:
                label: Practice label
                type: text
                default: Practice
              casestxt:
                label: Cases label
                type: text
                default: Cases
              studiotxt:
                label: Studio label
                type: text
                default: Studio
              logo:
                label: Logo
                type: files
                query: site.images
                multiple: false
                translate: false
                layout: cards
                size: small
                help: if none, default RalstonBau logo
          logos:
            type: files
            headline: Fichiers SVG
            layout: list
            template: logo
            info: "{{ file.dimensions }}"
            image:
              # ratio: 5/4
              back: white
              # cover: true
            # min: 1
            size: medium



      - width: 1/2
        fields:
          newsletterform:
            label: Newsletter form
            type: toggle
            text: Enable Newsletter form
            translate: false
          projectbgcolor:
            type: color
            editableAlpha: false
            default: "#000000"
            presets:
              - "#000000"
              - "#FFFFFF"
              - "#F2E0CD"
          projecttxtcolor:
            type: color
            editableAlpha: false
            default: "#FFFFFF"
            presets:
              - "#000000"
              - "#FFFFFF"
              - "#F2E0CD"
          description:
            label: Description
            type:  textarea
          keywords:
            label: Keywords
            type:  tags
          # ogimage:
          #   label: Site Thumbnail
          #   type:  url
          #   help:  URL of the thumbnail that will represent your website on the social networks.
          #   translate: false
  analytics:
    label: Analytics
    icon: refresh
    columns:
      - width: 3/4
        sections:
          main:
            type: matomo-main
      - width: 1/4
        sections:
          sidebar:
            type: matomo-sidebar
