title: Site


tabs:
  content:
    label: Content
    icon: text
    columns:
      - width: 1/2
        sections:
          cases: sections/cases
          practices: sections/practices
      - width: 1/2
        sections:
          notes: sections/notes
          pages:
            type: pages
            create: default
            template:
              - about
              - home
              - default
  settings:
    label: Settings
    icon: text
    columns:
      - width: 1/2
        fields:
          maintenance:
            label: Maintenance
            type: toggle
            text: Enable Maintenance
            translate: false
          share:
            label: Share on
            type: checkboxes
            options:
              facebook: Facebook
              twitter: Twitter
              pinterest: Pinterest
            help:  Enable the icons to share content on social network.
          facebook-id:
            label: Facebook page title
            type: text
          twitter-id:
            label: Twitter
            type: text
            placeholder: @twitter-account

      - width: 1/2
        fields:
          description:
            label: Description
            type:  textarea
          keywords:
            label: Keywords
            type:  tags
          ogimage:
            label: Site Thumbnail
            type:  url
            help:  URL of the thumbnail that will represent your website on the social networks.
            translate: false
