title: Site


tabs:
  content:
    label: Content
    icon: text
    columns:
      - width: 1
        fields:
          cases-practices:
            type: headline
            label: Cases & Practices
            numbered: false
      - width: 1/2
        sections:
          cases: sections/cases
      - width: 1/2
        sections:
          practices: sections/practices
      - width: 1/2
        sections:
          notes: sections/notes
      - width: 1/2
        sections:
          pages:
            type: pages
            create: default
            template:
              - about
              - home
              - default
              - map
      # - width: 1
      #   fields:
      #     practice-head:
      #       type: headline
      #       label: Practice
      #       numbered: false
      # - width: 1
      #   sections:
      #     practices:
      #       extends: sections/practices
      #       headline: Practices
            # status: draft

      # - width: 1/4
      #   sections:
      #     bigpictures:
      #       extends: sections/bigpictures
      #       status: listed
      # - width: 1/4
      #   sections:
      #     peoples:
      #       extends: sections/peoples
      #       status: listed

      # - width: 1/4
      #   sections:
      #     scenarios:
      #       extends: sections/scenarios
      #       status: listed

      # - width: 1/4
      #   sections:
      #     forms:
      #       extends: sections/forms
      #       status: listed

      - width: 1
        sections:
          products:
            extends: sections/order
            headline: Orders
            # status: draft

  settings:
    label: Settings
    icon: text
    columns:
      - width: 1/2
        sections:
          param1:
            type: fields 
            fields:
              practicetxt:
                label: Practice label
                type: text
                default: Practice
                width: 1/2
              casestxt:
                label: Cases label
                type: text
                default: Cases
                width: 1/2
              studiotxt:
                label: Studio label
                type: text
                default: Studio
                width: 1/2
              line:
                type: line
              bigpicturetxt:
                label: Big picture label
                type: text
                default: Big picture
                width: 1/2
              peopletxt:
                label: People label
                type: text
                default: People
                width: 1/2
              scenariotxt:
                label: Scenario label
                type: text
                default: Scenario
                width: 1/2
              formtxt:
                label: Form label
                type: text
                default: Form
                width: 1/2
              line3:
                type: line
              projectscategories:
                label: Categories for projects (cases)
                type: structure
                translate: false
                fields:
                  name_en:
                    label: Name (en, default)
                    type: text
                  name_fr:
                    label: Name (fr)
                    type: text
                  name_no:
                    label: Name (no)
                    type: text
      - width: 1/2
        sections:
          param2:
            type: fields 
            fields:
              maintenance:
                label: Maintenance
                type: toggle
                text: Enable Maintenance
                translate: false
                width: 1/2
              enablesearch:
                label: Enable searchbar
                type: toggle
                translate: false
                width: 1/2
              projectbgcolor:
                type: color
                editableAlpha: false
                translate: false
                default: "#000000"
                presets:
                  - "#000000"
                  - "#FFFFFF"
                  - "#F2E0CD"
                width: 1/2
              projecttxtcolor:
                type: color
                editableAlpha: false
                translate: false
                default: "#FFFFFF"
                presets:
                  - "#000000"
                  - "#FFFFFF"
                  - "#F2E0CD"
                width: 1/2
              newsletterform:
                label: Newsletter form
                type: toggle
                text: Enable Newsletter form
                translate: false
                width: 1/2
              tinyletterurl:
                label: Tinyletter form URL
                type: text
                translate: false
                width: 1/2
                when: 
                  newsletterform: true
              newslettertxt:
                label: Newsletter text
                type:  textarea
                when: 
                  newsletterform: true
              line2:
                type: line
              description:
                label: Description (SEO)
                type:  textarea
                buttons: false
                translate: false
              keywords:
                label: Keywords (SEO)
                type:  tags
                translate: false
              # ogimage:
              #   label: Site Thumbnail
              #   type:  url
              #   help:  URL of the thumbnail that will represent your website on the social networks.
              #   translate: false
              logo:
                label: Logo
                type: files
                query: site.images
                multiple: false
                translate: false
                layout: cards
                size: small
                help: if none, default RalstonBau logo
              thumbnail:
                label: Thumbnail
                type: files
                query: site.find('case').children.images
                multiple: false
                translate: false
                layout: cards
                size: small
          logos:
            type: files
            headline: Fichiers SVG
            layout: list
            template: logo
            info: "{{ file.dimensions }}"
            image:
              # ratio: 5/4
              back: white
              # cover: true
            # min: 1
            size: medium
  analytics:
    label: Analytics
    icon: refresh
    columns:
      - width: 3/4
        sections:
          main:
            type: matomo-main
      - width: 1/4
        sections:
          sidebar:
            type: matomo-sidebar
